/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DeletePanelView.java
 *
 * Created on 12 mai 2009, 11:56:08
 */

package fr.xlim.ssd.opalgui.view.delete;

/**
 *
 * @author Fox
 */
public class DeletePanelView extends javax.swing.JPanel {

    /** Creates new form DeletePanelView */
    public DeletePanelView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deletingOptionsRadioGroup = new javax.swing.ButtonGroup();
        aidSelectionPanel = new javax.swing.JPanel();
        aidSelectionLabel = new javax.swing.JLabel();
        aidSelectionComboBox = new javax.swing.JComboBox();
        deletingOptionsPanel = new javax.swing.JPanel();
        packageAndAppletsRadio = new javax.swing.JRadioButton();
        AppletRadio = new javax.swing.JRadioButton();
        packageRadio = new javax.swing.JRadioButton();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(fr.xlim.ssd.opalgui.OpalguiApp.class).getContext().getResourceMap(DeletePanelView.class);
        aidSelectionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("aidSelectionPanel.border.title"))); // NOI18N
        aidSelectionPanel.setName("aidSelectionPanel"); // NOI18N

        aidSelectionLabel.setText(resourceMap.getString("aidSelectionLabel.text")); // NOI18N
        aidSelectionLabel.setName("aidSelectionLabel"); // NOI18N

        aidSelectionComboBox.setEditable(true);
        aidSelectionComboBox.setName("aidSelectionComboBox"); // NOI18N

        javax.swing.GroupLayout aidSelectionPanelLayout = new javax.swing.GroupLayout(aidSelectionPanel);
        aidSelectionPanel.setLayout(aidSelectionPanelLayout);
        aidSelectionPanelLayout.setHorizontalGroup(
            aidSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aidSelectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aidSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aidSelectionComboBox, 0, 348, Short.MAX_VALUE)
                    .addComponent(aidSelectionLabel))
                .addContainerGap())
        );
        aidSelectionPanelLayout.setVerticalGroup(
            aidSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aidSelectionPanelLayout.createSequentialGroup()
                .addComponent(aidSelectionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aidSelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deletingOptionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("deletingOptionsPanel.border.title"))); // NOI18N
        deletingOptionsPanel.setName("deletingOptionsPanel"); // NOI18N

        deletingOptionsRadioGroup.add(packageAndAppletsRadio);
        packageAndAppletsRadio.setText(resourceMap.getString("packageAndAppletsRadio.text")); // NOI18N
        packageAndAppletsRadio.setName("packageAndAppletsRadio"); // NOI18N

        deletingOptionsRadioGroup.add(AppletRadio);
        AppletRadio.setText(resourceMap.getString("AppletRadio.text")); // NOI18N
        AppletRadio.setName("AppletRadio"); // NOI18N

        deletingOptionsRadioGroup.add(packageRadio);
        packageRadio.setText(resourceMap.getString("packageRadio.text")); // NOI18N
        packageRadio.setName("packageRadio"); // NOI18N

        javax.swing.GroupLayout deletingOptionsPanelLayout = new javax.swing.GroupLayout(deletingOptionsPanel);
        deletingOptionsPanel.setLayout(deletingOptionsPanelLayout);
        deletingOptionsPanelLayout.setHorizontalGroup(
            deletingOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletingOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deletingOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(packageAndAppletsRadio)
                    .addComponent(AppletRadio)
                    .addComponent(packageRadio))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        deletingOptionsPanelLayout.setVerticalGroup(
            deletingOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletingOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(packageAndAppletsRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AppletRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(packageRadio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletingOptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aidSelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aidSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletingOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AppletRadio;
    private javax.swing.JComboBox aidSelectionComboBox;
    private javax.swing.JLabel aidSelectionLabel;
    private javax.swing.JPanel aidSelectionPanel;
    private javax.swing.JPanel deletingOptionsPanel;
    private javax.swing.ButtonGroup deletingOptionsRadioGroup;
    private javax.swing.JRadioButton packageAndAppletsRadio;
    private javax.swing.JRadioButton packageRadio;
    // End of variables declaration//GEN-END:variables

}
