/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainMenuView.java
 *
 * Created on 11 mars 2009, 14:35:07
 */

package fr.xlim.ssd.opalgui.view.mainmenu;

import java.awt.Dimension;
import java.util.Enumeration;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;
import fr.xlim.ssd.opalgui.controller.MainMenuController;
import fr.xlim.ssd.opalgui.model.mode.ActionModel;
import fr.xlim.ssd.opalgui.model.mode.enumeration.ModeEnum;
import fr.xlim.ssd.opalgui.model.mode.ModeModelListener;
import fr.xlim.ssd.opalgui.model.mode.ModeModelChangedEvent;
import fr.xlim.ssd.opalgui.model.mode.ModeModel;
import fr.xlim.ssd.opalgui.model.mode.enumeration.ActionEnum;
import javax.swing.tree.TreeSelectionModel;

/**
 * This class reprensents the main menu. The menu allows the user to have an
 * immediate access to main actions (like Authenticate, Delete, ...).
 * View component of the MVC architecture.
 * @author Pequegnot David, Rispal Julie
 */
public class MainMenuView extends javax.swing.JPanel implements ModeModelListener {
    private ActionModel actionModel;

    /** Creates new form MainMenuView 
     * @param menuController Controller part of MVC architecture for the menu.
     * @param menuModel Model part of MVC architecture for the menu.
     */
    public MainMenuView(MainMenuController menuController, 
                        ModeModel          menuModel,
                        ActionModel        actionModel) {
        this.menuController = menuController;
        this.menuModel      = menuModel;
        this.actionModel    = actionModel ;
        
        initComponents();

        refreshView(menuModel.getCurrentMode());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuScrollPane = new javax.swing.JScrollPane();
        menuTree = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        modeButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(fr.xlim.ssd.opalgui.OpalguiApp.class).getContext().getResourceMap(MainMenuView.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        menuScrollPane.setName("menuScrollPane"); // NOI18N

        menuTree.setName("menuTree"); // NOI18N
        menuTree.setRootVisible(false);
        menuTree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION) ;
        menuTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                menuTreeValueChanged(evt);
            }
        });
        menuScrollPane.setViewportView(menuTree);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        modeButton.setText(resourceMap.getString("modeButton.text")); // NOI18N
        modeButton.setAlignmentX(0.5F);
        modeButton.setName("modeButton"); // NOI18N
        modeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(modeButton);

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setAlignmentX(0.5F);
        jButton2.setName("jButton2"); // NOI18N
        jPanel1.add(jButton2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menuScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeButtonActionPerformed
        if ( menuModel.getCurrentMode() == ModeEnum.STANDARD ) {
            this.menuController.notifyModeChanged(ModeEnum.ADVANCED);
        } else if ( menuModel.getCurrentMode() == ModeEnum.ADVANCED ) {
            this.menuController.notifyModeChanged(ModeEnum.STANDARD);
        }
    }//GEN-LAST:event_modeButtonActionPerformed

    /**
     * Notify the controller that the user want to switch to an other
     * action mode.
     * @param evt The event.
     */
    private void menuTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_menuTreeValueChanged
        DefaultMutableTreeNode node = (DefaultMutableTreeNode)menuTree.getLastSelectedPathComponent() ;
        if ( node == null ) {
            DefaultMutableTreeNode firstChild = (DefaultMutableTreeNode)menuTree.getModel().getRoot() ;
            menuTree.setSelectionPath( new TreePath( firstChild.getFirstChild() ) );
            if ( menuModel.getCurrentMode() == ModeEnum.STANDARD ) {
                menuController.notifyActionChanged( ActionEnum.DELETE_STANDARD );
            } else if ( menuModel.getCurrentMode() == ModeEnum.ADVANCED ) {
                menuController.notifyActionChanged( ActionEnum.AUTHENTIFICATE );
            }
        } else {
            DefaultMutableTreeNode parent = (DefaultMutableTreeNode)node.getParent() ;
            if ( "Authenticate".equals( node.toString() ) ) {
                if ( node.getLevel() == 1 ) {
                    menuController.notifyActionChanged( ActionEnum.AUTHENTIFICATE );
                } else if ( node.getLevel() == 2 ) {
                    if ( "Delete".equals(parent.toString()) ) {
                        menuController.notifyActionChanged( ActionEnum.DELETE_STANDARD_AUTHENTICATE );
                    } else if ( "Quick Load".equals(parent.toString()) ) {
                        menuController.notifyActionChanged( ActionEnum.QUICK_LOAD_AUTHENTICATE );
                    }
                }
            } else if ( "Delete".equals(node.toString()) ) {
                if( menuModel.getCurrentMode() == ModeEnum.STANDARD ) {
                    menuController.notifyActionChanged( ActionEnum.DELETE_STANDARD );
                } else if ( menuModel.getCurrentMode() == ModeEnum.ADVANCED ) {
                    menuController.notifyActionChanged( ActionEnum.DELETE_ADVANCED );
                }
            } else if ( "General".equals(node.toString()) ) {
                menuController.notifyActionChanged( ActionEnum.DELETE_STANDARD_GENERAL );
            } else if ( "Load".equals(node.toString()) ) {
                if ( node.getLevel() == 1 ) {
                    menuController.notifyActionChanged( ActionEnum.LOAD );
                } else if ( node.getLevel() == 2 ) {
                    if ( "Quick Load".equals( parent.toString()) ) {
                        menuController.notifyActionChanged( ActionEnum.QUICK_LOAD_LOAD );
                    }
                }
            } else if ( "Get Status".equals(node.toString()) ) {
                menuController.notifyActionChanged( ActionEnum.GET_STATUS );
            } else if ( "Install For Install".equals(node.toString()) ) {
                menuController.notifyActionChanged( ActionEnum.INSTALL_FOR_INSTALL );
            } else if ( "Load".equals(node.toString()) ) {
                if ( node.getLevel() == 1 ) {
                    menuController.notifyActionChanged( ActionEnum.LOAD );
                } else if ( node.getLevel() == 2 ) {
                    if ( "Quick Load".equals( parent.toString()) ) {
                        menuController.notifyActionChanged( ActionEnum.QUICK_LOAD_LOAD );
                    }
                }
            } else if ( "Install For Load".equals(node.toString()) ) {
                if ( node.getLevel() == 1 ) {
                    menuController.notifyActionChanged( ActionEnum.INSTALL_FOR_LOAD );
                } else if ( node.getLevel() == 2 ) {
                    if ( "Quick Load".equals( parent.toString()) ) {
                        menuController.notifyActionChanged( ActionEnum.QUICK_LOAD_INSTALL_FOR_LOAD );
                    }
                }
            } else if ( "Quick Load".equals(node.toString()) ) {
                menuController.notifyActionChanged( ActionEnum.QUICK_LOAD );
            } else if ( "Select".equals(node.toString()) ) {
                menuController.notifyActionChanged( ActionEnum.SELECT );
            } else if ( "Send APDU Command".equals(node.toString()) ) {
                menuController.notifyActionChanged( ActionEnum.SEND_APDU_COMMAND );
            } else {
                throw new UnsupportedOperationException( "Opération non supportée" );
            }
        }
    }//GEN-LAST:event_menuTreeValueChanged

    /**
     * When the modeButton is pressed, 
     * @param evt
     */
    private void refreshView(ModeEnum mode) {
        if (mode == ModeEnum.STANDARD) { // Creating a standard view
            modeButton.setText("Advanced mode");
        } else if (mode == ModeEnum.ADVANCED) { // Creating an advanced view
            modeButton.setText("Standard mode");
        } else {
            throw new UnsupportedOperationException("Not yet implemented!");
        }
        fillTree(mode);
    }

    private void fillTree(ModeEnum mode) {
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("root");
        DefaultMutableTreeNode level1 = null;
        DefaultMutableTreeNode level2 = null;
        if (mode == ModeEnum.STANDARD) { // The 'Standard mode'
            // The category 'Delete' contains items 'General' and
            // 'Authentification'
            level1 = new DefaultMutableTreeNode("Delete");
            level2 = new DefaultMutableTreeNode("General");
            level1.add(level2);
            level2 = new DefaultMutableTreeNode("Authenticate");
            level1.add(level2);
            root.add(level1);
            // The category 'QuickLoad' contains items 'Load',
            // 'Install for load' and 'Authentification'
            level1 = new DefaultMutableTreeNode("Quick Load");
            level2 = new DefaultMutableTreeNode("Load");
            level1.add(level2);
            level2 = new DefaultMutableTreeNode("Install For Load");
            level1.add(level2);
            level2 = new DefaultMutableTreeNode("Authenticate");
            level1.add(level2);
            root.add(level1);
            // Now, we have 'Select' and 'Send APDU command' to add in the tree
            // Select
            level1 = new DefaultMutableTreeNode("Select");
            root.add(level1);
            // Send APDU command
            level1 = new DefaultMutableTreeNode("Send APDU Command");
            root.add(level1);
            menuTree.setModel(new DefaultTreeModel(root));
            menuScrollPane.setMaximumSize(new Dimension(23000, fixedStandardHeight));
            menuScrollPane.setMinimumSize(new Dimension(fixedWidth, fixedStandardHeight));
            menuScrollPane.setPreferredSize(new Dimension(fixedWidth, fixedStandardHeight));
        } else if (mode == ModeEnum.ADVANCED) { // The 'Advanced mode'
            level1 = new DefaultMutableTreeNode("Authenticate");
            root.add(level1);
            level1 = new DefaultMutableTreeNode("Delete");
            root.add(level1);
            level1 = new DefaultMutableTreeNode("Get Status");
            root.add(level1);
            level1 = new DefaultMutableTreeNode("Install For Install");
            root.add(level1);
            level1 = new DefaultMutableTreeNode("Install For Load");
            root.add(level1);
            level1 = new DefaultMutableTreeNode("Load");
            root.add(level1);
            // The category 'QuickLoad' contains items 'Load',
            // 'Install for load' and 'Authentification'
            level1 = new DefaultMutableTreeNode("Quick Load");
            level2 = new DefaultMutableTreeNode("Load");
            level1.add(level2);
            level2 = new DefaultMutableTreeNode("Install For Load");
            level1.add(level2);
            level2 = new DefaultMutableTreeNode("Authenticate");
            level1.add(level2);
            root.add(level1);
            // Select
            level1 = new DefaultMutableTreeNode("Select");
            root.add(level1);
            // Send APDU command
            level1 = new DefaultMutableTreeNode("Send APDU Command");
            root.add(level1);
            menuTree.setModel(new DefaultTreeModel(root));
            menuScrollPane.setMaximumSize(new Dimension(23000,fixedAdvancedHeight));
            menuScrollPane.setMinimumSize(new Dimension(fixedWidth,fixedAdvancedHeight));
            menuScrollPane.setPreferredSize(new Dimension(fixedWidth,fixedAdvancedHeight));
        } else {
            throw new UnsupportedOperationException("Not implemented!");
        }
        expandAll(menuTree);
    }

    /**
     * The two next functions are used to expand all nodes from a tree.
     * @param tree The JTree object to expand all nodes.
     */
    private void expandAll(JTree tree) {
        TreeNode root = (TreeNode)tree.getModel().getRoot();

        // Expand all from root
        expandAll(tree, new TreePath(root));
    }

    /**
     * This function use a recursive call to expand all nodes. The call
     * is initiated by the previous function.
     * @param tree The tree to expand.
     * @param parent The parent tree path.
     */
    private void expandAll(JTree tree, TreePath parent) {
        TreeNode node = (TreeNode)parent.getLastPathComponent();
        if (node.getChildCount() > 0) {
            for (Enumeration e = node.children(); e.hasMoreElements(); ) {
                TreeNode n = (TreeNode)e.nextElement();
                TreePath path = parent.pathByAddingChild(n);
                expandAll(tree, path);
            }
        }
        tree.expandPath(parent);
    }

    @Override
    public void modeChanged(ModeModelChangedEvent event) {
        refreshView(event.getNewMode());
    }

    // No Matisse variables declaration
    private ModeModel menuModel;
    private MainMenuController menuController;

    private final int fixedWidth = 185;
    private final int fixedStandardHeight = 185;
    private final int fixedAdvancedHeight = 240;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane menuScrollPane;
    private javax.swing.JTree menuTree;
    private javax.swing.JButton modeButton;
    // End of variables declaration//GEN-END:variables

}
