/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoadView.java
 *
 * Created on 12 mai 2009, 18:38:04
 */

package fr.xlim.ssd.opalgui.view.load;

/**
 *
 * @author Fox
 */
public class LoadView extends javax.swing.JPanel {

    /** Creates new form LoadView */
    public LoadView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadFilePanel = new javax.swing.JPanel();
        loadFileLabel = new javax.swing.JLabel();
        loadFileTextFile = new javax.swing.JTextField();
        loadFileButton = new javax.swing.JButton();
        blockSizePanel = new javax.swing.JPanel();
        blockSizeCheck = new javax.swing.JCheckBox();
        blockSizeTextField = new javax.swing.JTextField();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(fr.xlim.ssd.opalgui.OpalguiApp.class).getContext().getResourceMap(LoadView.class);
        loadFilePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("loadFilePanel.border.title"))); // NOI18N
        loadFilePanel.setName("loadFilePanel"); // NOI18N

        loadFileLabel.setText(resourceMap.getString("loadFileLabel.text")); // NOI18N
        loadFileLabel.setName("loadFileLabel"); // NOI18N

        loadFileTextFile.setText(resourceMap.getString("loadFileTextFile.text")); // NOI18N
        loadFileTextFile.setName("loadFileTextFile"); // NOI18N

        loadFileButton.setText(resourceMap.getString("loadFileButton.text")); // NOI18N
        loadFileButton.setName("loadFileButton"); // NOI18N

        javax.swing.GroupLayout loadFilePanelLayout = new javax.swing.GroupLayout(loadFilePanel);
        loadFilePanel.setLayout(loadFilePanelLayout);
        loadFilePanelLayout.setHorizontalGroup(
            loadFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadFilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loadFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadFileLabel)
                    .addComponent(loadFileTextFile, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadFileButton)
                .addContainerGap())
        );
        loadFilePanelLayout.setVerticalGroup(
            loadFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadFilePanelLayout.createSequentialGroup()
                .addComponent(loadFileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loadFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadFileTextFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadFileButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        blockSizePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("blockSizePanel.border.title"))); // NOI18N
        blockSizePanel.setName("blockSizePanel"); // NOI18N

        blockSizeCheck.setText(resourceMap.getString("blockSizeCheck.text")); // NOI18N
        blockSizeCheck.setName("blockSizeCheck"); // NOI18N

        blockSizeTextField.setText(resourceMap.getString("blockSizeTextField.text")); // NOI18N
        blockSizeTextField.setName("blockSizeTextField"); // NOI18N

        javax.swing.GroupLayout blockSizePanelLayout = new javax.swing.GroupLayout(blockSizePanel);
        blockSizePanel.setLayout(blockSizePanelLayout);
        blockSizePanelLayout.setHorizontalGroup(
            blockSizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockSizePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blockSizeCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blockSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        blockSizePanelLayout.setVerticalGroup(
            blockSizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockSizePanelLayout.createSequentialGroup()
                .addGroup(blockSizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blockSizeCheck)
                    .addComponent(blockSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(blockSizePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadFilePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loadFilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blockSizePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox blockSizeCheck;
    private javax.swing.JPanel blockSizePanel;
    private javax.swing.JTextField blockSizeTextField;
    private javax.swing.JButton loadFileButton;
    private javax.swing.JLabel loadFileLabel;
    private javax.swing.JPanel loadFilePanel;
    private javax.swing.JTextField loadFileTextFile;
    // End of variables declaration//GEN-END:variables

}
