/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GetStatusView.java
 *
 * Created on 12 mai 2009, 13:06:48
 */

package fr.xlim.ssd.opalgui.view.getstatus;

/**
 *
 * @author Fox
 */
public class GetStatusView extends javax.swing.JPanel {

    /** Creates new form GetStatusView */
    public GetStatusView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prefDeleteGroup = new javax.swing.ButtonGroup();
        prefSearchGroup = new javax.swing.ButtonGroup();
        preferencesPanel = new javax.swing.JPanel();
        isdPrefRadioButton = new javax.swing.JRadioButton();
        appAndSDPrefRadioButton = new javax.swing.JRadioButton();
        execLoadFilesPrefRadioButton = new javax.swing.JRadioButton();
        execLoadFilesAndModulesPrefRadioButton = new javax.swing.JRadioButton();
        searchQualifierPanel = new javax.swing.JPanel();
        allRadio = new javax.swing.JRadioButton();
        selectionRadio = new javax.swing.JRadioButton();
        selectionAIDTextField = new javax.swing.JTextField();
        selectionLabel = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(fr.xlim.ssd.opalgui.OpalguiApp.class).getContext().getResourceMap(GetStatusView.class);
        preferencesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("preferencesPanel.border.title"))); // NOI18N
        preferencesPanel.setName("preferencesPanel"); // NOI18N

        prefDeleteGroup.add(isdPrefRadioButton);
        isdPrefRadioButton.setText(resourceMap.getString("isdPrefRadioButton.text")); // NOI18N
        isdPrefRadioButton.setName("isdPrefRadioButton"); // NOI18N

        prefDeleteGroup.add(appAndSDPrefRadioButton);
        appAndSDPrefRadioButton.setText(resourceMap.getString("appAndSDPrefRadioButton.text")); // NOI18N
        appAndSDPrefRadioButton.setName("appAndSDPrefRadioButton"); // NOI18N

        prefDeleteGroup.add(execLoadFilesPrefRadioButton);
        execLoadFilesPrefRadioButton.setText(resourceMap.getString("execLoadFilesPrefRadioButton.text")); // NOI18N
        execLoadFilesPrefRadioButton.setName("execLoadFilesPrefRadioButton"); // NOI18N

        prefDeleteGroup.add(execLoadFilesAndModulesPrefRadioButton);
        execLoadFilesAndModulesPrefRadioButton.setText(resourceMap.getString("execLoadFilesAndModulesPrefRadioButton.text")); // NOI18N
        execLoadFilesAndModulesPrefRadioButton.setName("execLoadFilesAndModulesPrefRadioButton"); // NOI18N

        javax.swing.GroupLayout preferencesPanelLayout = new javax.swing.GroupLayout(preferencesPanel);
        preferencesPanel.setLayout(preferencesPanelLayout);
        preferencesPanelLayout.setHorizontalGroup(
            preferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preferencesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(preferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isdPrefRadioButton)
                    .addComponent(appAndSDPrefRadioButton)
                    .addComponent(execLoadFilesPrefRadioButton)
                    .addComponent(execLoadFilesAndModulesPrefRadioButton))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        preferencesPanelLayout.setVerticalGroup(
            preferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preferencesPanelLayout.createSequentialGroup()
                .addComponent(isdPrefRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appAndSDPrefRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(execLoadFilesPrefRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(execLoadFilesAndModulesPrefRadioButton))
        );

        searchQualifierPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("searchQualifierPanel.border.title"))); // NOI18N
        searchQualifierPanel.setName("searchQualifierPanel"); // NOI18N

        prefSearchGroup.add(allRadio);
        allRadio.setText(resourceMap.getString("allRadio.text")); // NOI18N
        allRadio.setName("allRadio"); // NOI18N

        prefSearchGroup.add(selectionRadio);
        selectionRadio.setText(resourceMap.getString("selectionRadio.text")); // NOI18N
        selectionRadio.setName("selectionRadio"); // NOI18N

        selectionAIDTextField.setText(resourceMap.getString("selectionAIDTextField.text")); // NOI18N
        selectionAIDTextField.setName("selectionAIDTextField"); // NOI18N

        selectionLabel.setText(resourceMap.getString("selectionLabel.text")); // NOI18N
        selectionLabel.setName("selectionLabel"); // NOI18N

        javax.swing.GroupLayout searchQualifierPanelLayout = new javax.swing.GroupLayout(searchQualifierPanel);
        searchQualifierPanel.setLayout(searchQualifierPanelLayout);
        searchQualifierPanelLayout.setHorizontalGroup(
            searchQualifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchQualifierPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchQualifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchQualifierPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(selectionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectionAIDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
                    .addComponent(allRadio)
                    .addComponent(selectionRadio))
                .addContainerGap())
        );
        searchQualifierPanelLayout.setVerticalGroup(
            searchQualifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchQualifierPanelLayout.createSequentialGroup()
                .addComponent(allRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectionRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchQualifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectionLabel)
                    .addComponent(selectionAIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchQualifierPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(preferencesPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(preferencesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchQualifierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allRadio;
    private javax.swing.JRadioButton appAndSDPrefRadioButton;
    private javax.swing.JRadioButton execLoadFilesAndModulesPrefRadioButton;
    private javax.swing.JRadioButton execLoadFilesPrefRadioButton;
    private javax.swing.JRadioButton isdPrefRadioButton;
    private javax.swing.ButtonGroup prefDeleteGroup;
    private javax.swing.ButtonGroup prefSearchGroup;
    private javax.swing.JPanel preferencesPanel;
    private javax.swing.JPanel searchQualifierPanel;
    private javax.swing.JTextField selectionAIDTextField;
    private javax.swing.JLabel selectionLabel;
    private javax.swing.JRadioButton selectionRadio;
    // End of variables declaration//GEN-END:variables

}
