/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProfileManagement.java
 *
 * Created on 11 mai 2009, 23:45:37
 */

package fr.xlim.ssd.opalgui.view.authenticate;

import fr.xlim.ssd.opal.library.params.CardConfig;
import fr.xlim.ssd.opal.library.params.CardConfigNotFoundException;
import fr.xlim.ssd.opal.library.utilities.Conversion;
import fr.xlim.ssd.opalgui.controller.authentication.AuthenticationController;
import fr.xlim.ssd.opalgui.model.authenticate.AuthenticationModel;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Fox
 */
public class ProfileManagement extends javax.swing.JDialog {
    AuthenticationController controller = null ;
    AuthenticationModel      model      = null ;
    ProfileManagement.Mode   mode       = null ;

    /**
     * The enum Mode defines the mode of the JDialog to display :
     * ADD when we want to add a profile ;
     * MODIFY when we want to modify a profile.
     */
    public enum Mode {
        ADD,
        MODIFY
    }

    /** Creates new form ProfileManagement
     * This constructor is used to add a profile.
     * @param parent The parent frame
     * @param modal Is the current window modal ?
     * @param controller The controller part of the MVC architecture.
     */
    public ProfileManagement( java.awt.Frame parent, boolean modal,
            AuthenticationController controller ) {
        super(parent, modal);
        this.controller = controller ;
        this.mode       = ProfileManagement.Mode.ADD ;
        initComponents();
        addButton.setText( "Add" ) ;
    }

    /** Creates new form ProfileManagement
     * This constructor is used to modify the selected profile.
     * @param parent The parent frame
     * @param modal Is the current window modal ?
     * @param controller The controller part of the MVC architecture.
     * @param model The model part of the MVC architecture. It also defines
     * the current profile.
     */
    public ProfileManagement( java.awt.Frame parent, boolean modal,
            AuthenticationController controller,
            AuthenticationModel      model     ) {
        super(parent, modal);
        this.controller = controller ;
        this.model      = model      ;
        this.mode       = ProfileManagement.Mode.MODIFY ;
        initComponents();
        fillWithCurrentCardSelection();
        addButton.setText( "Modify" ) ;
    }

    /**
     * This function can be only called in the "MODIFY" mode.
     * It fills the form with current selection in the model.
     */
    private void fillWithCurrentCardSelection() {
        if ( this.mode == ProfileManagement.Mode.MODIFY ) {
            try {
                CardConfig card = this.model.getSelectedCard();
                profileNameValueTextField.setText(
                        this.model.getSelectedCardName() );
                defaultImplementationValueComboBox.addItem(
                        card.getImplementation() );
                if ( card.getTransmissionProtocol().equals("T=0") ) {
                    transmissionProtocolValueComboBox.setSelectedIndex(0);
                } else {
                    transmissionProtocolValueComboBox.setSelectedIndex(1);
                }
                isdAIDValueTextField.setText(
                        Conversion.arrayToHex( card.getIssuerSecurityDomainAID() ) );
                switch ( card.getSCKeys()[0].getType() ) {
                    case DES_ECB :
                        keyTypeValueComboBox.setSelectedIndex(0);
                        break;
                    case MOTHER_KEY :
                        keyTypeValueComboBox.setSelectedIndex(1);
                        break;
                    default :
                        keyTypeValueComboBox.setSelectedIndex(0);
                }
                // TODO
            } catch (CardConfigNotFoundException ex) {
                Logger.getLogger(ProfileManagement.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profileNameLabel = new javax.swing.JLabel();
        profileNameValueTextField = new javax.swing.JTextField();
        defaultImplementationLabel = new javax.swing.JLabel();
        defaultImplementationValueComboBox = new javax.swing.JComboBox();
        transmissionProtocolLabel = new javax.swing.JLabel();
        transmissionProtocolValueComboBox = new javax.swing.JComboBox();
        defaultSCPLabel = new javax.swing.JLabel();
        defaultSCPValueComboBox = new javax.swing.JComboBox();
        addButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        isdAIDLabel = new javax.swing.JLabel();
        isdAIDValueTextField = new javax.swing.JTextField();
        keyTypeLabel = new javax.swing.JLabel();
        keyTypeValueComboBox = new javax.swing.JComboBox();
        keyConfigurationPanel = new javax.swing.JPanel();
        s_encPanel = new javax.swing.JPanel();
        s_encIndexLabel = new javax.swing.JLabel();
        s_encIndexValueTextField = new javax.swing.JTextField();
        s_encValueLabel = new javax.swing.JLabel();
        s_encValueValueTextField = new javax.swing.JTextField();
        s_macPanel = new javax.swing.JPanel();
        s_macIndexLabel = new javax.swing.JLabel();
        s_macIndexValueTextField = new javax.swing.JTextField();
        s_macValueLabel = new javax.swing.JLabel();
        s_macValueValueTextField = new javax.swing.JTextField();
        dekPanel = new javax.swing.JPanel();
        dekIndexLabel = new javax.swing.JLabel();
        dekIndexValueTextField = new javax.swing.JTextField();
        dekValueLabel = new javax.swing.JLabel();
        dekValueValueTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 0));
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(fr.xlim.ssd.opalgui.OpalguiApp.class).getContext().getResourceMap(ProfileManagement.class);
        profileNameLabel.setText(resourceMap.getString("profileNameLabel.text")); // NOI18N
        profileNameLabel.setName("profileNameLabel"); // NOI18N

        profileNameValueTextField.setText(resourceMap.getString("profileNameValueTextField.text")); // NOI18N
        profileNameValueTextField.setName("profileNameValueTextField"); // NOI18N

        defaultImplementationLabel.setText(resourceMap.getString("defaultImplementationLabel.text")); // NOI18N
        defaultImplementationLabel.setName("defaultImplementationLabel"); // NOI18N

        defaultImplementationValueComboBox.setName("defaultImplementationValueComboBox"); // NOI18N

        transmissionProtocolLabel.setText(resourceMap.getString("transmissionProtocolLabel.text")); // NOI18N
        transmissionProtocolLabel.setName("transmissionProtocolLabel"); // NOI18N

        transmissionProtocolValueComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "T=0", "T=1" }));
        transmissionProtocolValueComboBox.setName("transmissionProtocolValueComboBox"); // NOI18N

        defaultSCPLabel.setText(resourceMap.getString("defaultSCPLabel.text")); // NOI18N
        defaultSCPLabel.setName("defaultSCPLabel"); // NOI18N

        defaultSCPValueComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SCP01 [deprecated]", "SCP02 [not yet implemented]", "SCP10 [not yet implemented]" }));
        defaultSCPValueComboBox.setName("defaultSCPValueComboBox"); // NOI18N

        addButton.setText(resourceMap.getString("addButton.text")); // NOI18N
        addButton.setName("addButton"); // NOI18N

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N

        isdAIDLabel.setText(resourceMap.getString("isdAIDLabel.text")); // NOI18N
        isdAIDLabel.setName("isdAIDLabel"); // NOI18N

        isdAIDValueTextField.setText(resourceMap.getString("isdAIDValueTextField.text")); // NOI18N
        isdAIDValueTextField.setName("isdAIDValueTextField"); // NOI18N

        keyTypeLabel.setText(resourceMap.getString("keyTypeLabel.text")); // NOI18N
        keyTypeLabel.setName("keyTypeLabel"); // NOI18N

        keyTypeValueComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Triple DES in ECB mode", "SCGEMVISA", "SCGEMVISA2" }));
        keyTypeValueComboBox.setName("keyTypeValueComboBox"); // NOI18N

        keyConfigurationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("keyConfigurationPanel.border.title"))); // NOI18N
        keyConfigurationPanel.setName("keyConfigurationPanel"); // NOI18N

        s_encPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("s_encPanel.border.title"))); // NOI18N
        s_encPanel.setName("s_encPanel"); // NOI18N

        s_encIndexLabel.setText(resourceMap.getString("s_encIndexLabel.text")); // NOI18N
        s_encIndexLabel.setName("s_encIndexLabel"); // NOI18N

        s_encIndexValueTextField.setText(resourceMap.getString("s_encIndexValueTextField.text")); // NOI18N
        s_encIndexValueTextField.setName("s_encIndexValueTextField"); // NOI18N

        s_encValueLabel.setText(resourceMap.getString("s_encValueLabel.text")); // NOI18N
        s_encValueLabel.setName("s_encValueLabel"); // NOI18N

        s_encValueValueTextField.setText(resourceMap.getString("s_encValueValueTextField.text")); // NOI18N
        s_encValueValueTextField.setName("s_encValueValueTextField"); // NOI18N

        javax.swing.GroupLayout s_encPanelLayout = new javax.swing.GroupLayout(s_encPanel);
        s_encPanel.setLayout(s_encPanelLayout);
        s_encPanelLayout.setHorizontalGroup(
            s_encPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(s_encPanelLayout.createSequentialGroup()
                .addGroup(s_encPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s_encValueLabel)
                    .addComponent(s_encIndexLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(s_encPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(s_encPanelLayout.createSequentialGroup()
                        .addComponent(s_encIndexValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(294, Short.MAX_VALUE))
                    .addComponent(s_encValueValueTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)))
        );
        s_encPanelLayout.setVerticalGroup(
            s_encPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(s_encPanelLayout.createSequentialGroup()
                .addGroup(s_encPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_encIndexLabel)
                    .addComponent(s_encIndexValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(s_encPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_encValueLabel)
                    .addComponent(s_encValueValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        s_macPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("s_macPanel.border.title"))); // NOI18N
        s_macPanel.setName("s_macPanel"); // NOI18N

        s_macIndexLabel.setText(resourceMap.getString("s_macIndexLabel.text")); // NOI18N
        s_macIndexLabel.setName("s_macIndexLabel"); // NOI18N

        s_macIndexValueTextField.setName("s_macIndexValueTextField"); // NOI18N

        s_macValueLabel.setText(resourceMap.getString("s_macValueLabel.text")); // NOI18N
        s_macValueLabel.setName("s_macValueLabel"); // NOI18N

        s_macValueValueTextField.setName("s_macValueValueTextField"); // NOI18N

        javax.swing.GroupLayout s_macPanelLayout = new javax.swing.GroupLayout(s_macPanel);
        s_macPanel.setLayout(s_macPanelLayout);
        s_macPanelLayout.setHorizontalGroup(
            s_macPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(s_macPanelLayout.createSequentialGroup()
                .addGroup(s_macPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s_macValueLabel)
                    .addComponent(s_macIndexLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(s_macPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(s_macPanelLayout.createSequentialGroup()
                        .addComponent(s_macIndexValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(294, Short.MAX_VALUE))
                    .addComponent(s_macValueValueTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)))
        );
        s_macPanelLayout.setVerticalGroup(
            s_macPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(s_macPanelLayout.createSequentialGroup()
                .addGroup(s_macPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_macIndexLabel)
                    .addComponent(s_macIndexValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(s_macPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_macValueLabel)
                    .addComponent(s_macValueValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        dekPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("dekPanel.border.title"))); // NOI18N
        dekPanel.setName("dekPanel"); // NOI18N

        dekIndexLabel.setText(resourceMap.getString("dekIndexLabel.text")); // NOI18N
        dekIndexLabel.setName("dekIndexLabel"); // NOI18N

        dekIndexValueTextField.setName("dekIndexValueTextField"); // NOI18N

        dekValueLabel.setText(resourceMap.getString("dekValueLabel.text")); // NOI18N
        dekValueLabel.setName("dekValueLabel"); // NOI18N

        dekValueValueTextField.setName("dekValueValueTextField"); // NOI18N

        javax.swing.GroupLayout dekPanelLayout = new javax.swing.GroupLayout(dekPanel);
        dekPanel.setLayout(dekPanelLayout);
        dekPanelLayout.setHorizontalGroup(
            dekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dekPanelLayout.createSequentialGroup()
                .addGroup(dekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dekValueLabel)
                    .addComponent(dekIndexLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dekPanelLayout.createSequentialGroup()
                        .addComponent(dekIndexValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(294, Short.MAX_VALUE))
                    .addComponent(dekValueValueTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)))
        );
        dekPanelLayout.setVerticalGroup(
            dekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dekPanelLayout.createSequentialGroup()
                .addGroup(dekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dekIndexLabel)
                    .addComponent(dekIndexValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dekValueLabel)
                    .addComponent(dekValueValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout keyConfigurationPanelLayout = new javax.swing.GroupLayout(keyConfigurationPanel);
        keyConfigurationPanel.setLayout(keyConfigurationPanelLayout);
        keyConfigurationPanelLayout.setHorizontalGroup(
            keyConfigurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(s_encPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(s_macPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dekPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        keyConfigurationPanelLayout.setVerticalGroup(
            keyConfigurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keyConfigurationPanelLayout.createSequentialGroup()
                .addComponent(s_encPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s_macPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dekPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(keyConfigurationPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(profileNameLabel)
                        .addGap(55, 55, 55)
                        .addComponent(profileNameValueTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(defaultImplementationLabel)
                            .addComponent(transmissionProtocolLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transmissionProtocolValueComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(defaultImplementationValueComboBox, 0, 269, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(isdAIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isdAIDValueTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(defaultSCPLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(defaultSCPValueComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(keyTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keyTypeValueComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profileNameLabel)
                    .addComponent(profileNameValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defaultImplementationValueComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(defaultImplementationLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transmissionProtocolValueComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transmissionProtocolLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isdAIDLabel)
                    .addComponent(isdAIDValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defaultSCPLabel)
                    .addComponent(defaultSCPValueComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keyTypeLabel)
                    .addComponent(keyTypeValueComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keyConfigurationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(addButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ProfileManagement dialog = new ProfileManagement(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel defaultImplementationLabel;
    private javax.swing.JComboBox defaultImplementationValueComboBox;
    private javax.swing.JLabel defaultSCPLabel;
    private javax.swing.JComboBox defaultSCPValueComboBox;
    private javax.swing.JLabel dekIndexLabel;
    private javax.swing.JTextField dekIndexValueTextField;
    private javax.swing.JPanel dekPanel;
    private javax.swing.JLabel dekValueLabel;
    private javax.swing.JTextField dekValueValueTextField;
    private javax.swing.JLabel isdAIDLabel;
    private javax.swing.JTextField isdAIDValueTextField;
    private javax.swing.JPanel keyConfigurationPanel;
    private javax.swing.JLabel keyTypeLabel;
    private javax.swing.JComboBox keyTypeValueComboBox;
    private javax.swing.JLabel profileNameLabel;
    private javax.swing.JTextField profileNameValueTextField;
    private javax.swing.JLabel s_encIndexLabel;
    private javax.swing.JTextField s_encIndexValueTextField;
    private javax.swing.JPanel s_encPanel;
    private javax.swing.JLabel s_encValueLabel;
    private javax.swing.JTextField s_encValueValueTextField;
    private javax.swing.JLabel s_macIndexLabel;
    private javax.swing.JTextField s_macIndexValueTextField;
    private javax.swing.JPanel s_macPanel;
    private javax.swing.JLabel s_macValueLabel;
    private javax.swing.JTextField s_macValueValueTextField;
    private javax.swing.JLabel transmissionProtocolLabel;
    private javax.swing.JComboBox transmissionProtocolValueComboBox;
    // End of variables declaration//GEN-END:variables

}
