/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InstallForInstallView.java
 *
 * Created on 12 mai 2009, 17:01:08
 */

package fr.xlim.ssd.opalgui.view.installforinstall;

/**
 *
 * @author Fox
 */
public class InstallForInstallView extends javax.swing.JPanel {

    /** Creates new form InstallForInstallView */
    public InstallForInstallView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aidsPanel = new javax.swing.JPanel();
        executableLoadFileAIDPanel = new javax.swing.JPanel();
        executableLoadFileAIDComboBox = new javax.swing.JComboBox();
        executableModuleAIDPanel = new javax.swing.JPanel();
        executableModuleAIDComboBox = new javax.swing.JComboBox();
        applicationAIDPanel = new javax.swing.JPanel();
        applicationAIDComboBox = new javax.swing.JComboBox();
        privilegesLabel = new javax.swing.JLabel();
        privilegesValueTextField = new javax.swing.JTextField();
        installCommandParametersPanel = new javax.swing.JPanel();
        installCommandParametersScrollPane = new javax.swing.JScrollPane();
        installCommandParametersTextArea = new javax.swing.JTextArea();
        editPrivilegesButton = new javax.swing.JButton();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(fr.xlim.ssd.opalgui.OpalguiApp.class).getContext().getResourceMap(InstallForInstallView.class);
        aidsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("aidsPanel.border.title"))); // NOI18N
        aidsPanel.setName("aidsPanel"); // NOI18N

        executableLoadFileAIDPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("executableLoadFileAIDPanel.border.title"))); // NOI18N
        executableLoadFileAIDPanel.setName("executableLoadFileAIDPanel"); // NOI18N

        executableLoadFileAIDComboBox.setEditable(true);
        executableLoadFileAIDComboBox.setName("executableLoadFileAIDComboBox"); // NOI18N

        javax.swing.GroupLayout executableLoadFileAIDPanelLayout = new javax.swing.GroupLayout(executableLoadFileAIDPanel);
        executableLoadFileAIDPanel.setLayout(executableLoadFileAIDPanelLayout);
        executableLoadFileAIDPanelLayout.setHorizontalGroup(
            executableLoadFileAIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(executableLoadFileAIDPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(executableLoadFileAIDComboBox, 0, 471, Short.MAX_VALUE)
                .addContainerGap())
        );
        executableLoadFileAIDPanelLayout.setVerticalGroup(
            executableLoadFileAIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(executableLoadFileAIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        executableModuleAIDPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("executableModuleAIDPanel.border.title"))); // NOI18N
        executableModuleAIDPanel.setName("executableModuleAIDPanel"); // NOI18N

        executableModuleAIDComboBox.setEditable(true);
        executableModuleAIDComboBox.setName("executableModuleAIDComboBox"); // NOI18N

        javax.swing.GroupLayout executableModuleAIDPanelLayout = new javax.swing.GroupLayout(executableModuleAIDPanel);
        executableModuleAIDPanel.setLayout(executableModuleAIDPanelLayout);
        executableModuleAIDPanelLayout.setHorizontalGroup(
            executableModuleAIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(executableModuleAIDPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(executableModuleAIDComboBox, 0, 471, Short.MAX_VALUE)
                .addContainerGap())
        );
        executableModuleAIDPanelLayout.setVerticalGroup(
            executableModuleAIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(executableModuleAIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        applicationAIDPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("applicationAIDPanel.border.title"))); // NOI18N
        applicationAIDPanel.setName("applicationAIDPanel"); // NOI18N

        applicationAIDComboBox.setEditable(true);
        applicationAIDComboBox.setName("applicationAIDComboBox"); // NOI18N

        javax.swing.GroupLayout applicationAIDPanelLayout = new javax.swing.GroupLayout(applicationAIDPanel);
        applicationAIDPanel.setLayout(applicationAIDPanelLayout);
        applicationAIDPanelLayout.setHorizontalGroup(
            applicationAIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationAIDPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(applicationAIDComboBox, 0, 471, Short.MAX_VALUE)
                .addContainerGap())
        );
        applicationAIDPanelLayout.setVerticalGroup(
            applicationAIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(applicationAIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout aidsPanelLayout = new javax.swing.GroupLayout(aidsPanel);
        aidsPanel.setLayout(aidsPanelLayout);
        aidsPanelLayout.setHorizontalGroup(
            aidsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aidsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aidsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(applicationAIDPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(executableLoadFileAIDPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(executableModuleAIDPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        aidsPanelLayout.setVerticalGroup(
            aidsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aidsPanelLayout.createSequentialGroup()
                .addComponent(executableLoadFileAIDPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(executableModuleAIDPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(applicationAIDPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        privilegesLabel.setText(resourceMap.getString("privilegesLabel.text")); // NOI18N
        privilegesLabel.setName("privilegesLabel"); // NOI18N

        privilegesValueTextField.setText(resourceMap.getString("privilegesValueTextField.text")); // NOI18N
        privilegesValueTextField.setName("privilegesValueTextField"); // NOI18N

        installCommandParametersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("installCommandParametersPanel.border.title"))); // NOI18N
        installCommandParametersPanel.setName("installCommandParametersPanel"); // NOI18N

        installCommandParametersScrollPane.setName("installCommandParametersScrollPane"); // NOI18N

        installCommandParametersTextArea.setColumns(20);
        installCommandParametersTextArea.setRows(2);
        installCommandParametersTextArea.setName("installCommandParametersTextArea"); // NOI18N
        installCommandParametersScrollPane.setViewportView(installCommandParametersTextArea);

        javax.swing.GroupLayout installCommandParametersPanelLayout = new javax.swing.GroupLayout(installCommandParametersPanel);
        installCommandParametersPanel.setLayout(installCommandParametersPanelLayout);
        installCommandParametersPanelLayout.setHorizontalGroup(
            installCommandParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(installCommandParametersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(installCommandParametersScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );
        installCommandParametersPanelLayout.setVerticalGroup(
            installCommandParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(installCommandParametersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        editPrivilegesButton.setText(resourceMap.getString("editPrivilegesButton.text")); // NOI18N
        editPrivilegesButton.setName("editPrivilegesButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aidsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(privilegesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(privilegesValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editPrivilegesButton))
                    .addComponent(installCommandParametersPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aidsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(privilegesLabel)
                    .addComponent(privilegesValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editPrivilegesButton))
                .addGap(18, 18, 18)
                .addComponent(installCommandParametersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aidsPanel;
    private javax.swing.JComboBox applicationAIDComboBox;
    private javax.swing.JPanel applicationAIDPanel;
    private javax.swing.JButton editPrivilegesButton;
    private javax.swing.JComboBox executableLoadFileAIDComboBox;
    private javax.swing.JPanel executableLoadFileAIDPanel;
    private javax.swing.JComboBox executableModuleAIDComboBox;
    private javax.swing.JPanel executableModuleAIDPanel;
    private javax.swing.JPanel installCommandParametersPanel;
    private javax.swing.JScrollPane installCommandParametersScrollPane;
    private javax.swing.JTextArea installCommandParametersTextArea;
    private javax.swing.JLabel privilegesLabel;
    private javax.swing.JTextField privilegesValueTextField;
    // End of variables declaration//GEN-END:variables

}
