/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectView.java
 *
 * Created on 12 mai 2009, 19:39:48
 */

package fr.xlim.ssd.opalgui.view.select;

/**
 *
 * @author Fox
 */
public class SelectView extends javax.swing.JPanel {

    /** Creates new form SelectView */
    public SelectView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectParametersPanel = new javax.swing.JPanel();
        selectParametersComboBox = new javax.swing.JComboBox();
        selectParametersLabel = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(fr.xlim.ssd.opalgui.OpalguiApp.class).getContext().getResourceMap(SelectView.class);
        selectParametersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("selectParametersPanel.border.title"))); // NOI18N
        selectParametersPanel.setName("selectParametersPanel"); // NOI18N

        selectParametersComboBox.setEditable(true);
        selectParametersComboBox.setName("selectParametersComboBox"); // NOI18N

        selectParametersLabel.setText(resourceMap.getString("selectParametersLabel.text")); // NOI18N
        selectParametersLabel.setName("selectParametersLabel"); // NOI18N

        javax.swing.GroupLayout selectParametersPanelLayout = new javax.swing.GroupLayout(selectParametersPanel);
        selectParametersPanel.setLayout(selectParametersPanelLayout);
        selectParametersPanelLayout.setHorizontalGroup(
            selectParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectParametersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectParametersComboBox, 0, 348, Short.MAX_VALUE)
                    .addComponent(selectParametersLabel))
                .addContainerGap())
        );
        selectParametersPanelLayout.setVerticalGroup(
            selectParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectParametersPanelLayout.createSequentialGroup()
                .addComponent(selectParametersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectParametersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectParametersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectParametersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox selectParametersComboBox;
    private javax.swing.JLabel selectParametersLabel;
    private javax.swing.JPanel selectParametersPanel;
    // End of variables declaration//GEN-END:variables

}
