/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InstallForLoadView.java
 *
 * Created on 12 mai 2009, 18:26:12
 */

package fr.xlim.ssd.opalgui.view.installforload;

/**
 *
 * @author Fox
 */
public class InstallForLoadView extends javax.swing.JPanel {

    /** Creates new form InstallForLoadView */
    public InstallForLoadView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aidsPanel = new javax.swing.JPanel();
        loadFileAIDPanel = new javax.swing.JPanel();
        loadFileAIDComboBox = new javax.swing.JComboBox();
        securityDomainAIDPanel = new javax.swing.JPanel();
        securityDomainAIDComboBox = new javax.swing.JComboBox();
        loadParametersPanel = new javax.swing.JPanel();
        loadParametersScrollPanel = new javax.swing.JScrollPane();
        loadParametersTextArea = new javax.swing.JTextArea();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(fr.xlim.ssd.opalgui.OpalguiApp.class).getContext().getResourceMap(InstallForLoadView.class);
        aidsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("aidsPanel.border.title"))); // NOI18N
        aidsPanel.setName("aidsPanel"); // NOI18N

        loadFileAIDPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("loadFileAIDPanel.border.title"))); // NOI18N
        loadFileAIDPanel.setName("loadFileAIDPanel"); // NOI18N

        loadFileAIDComboBox.setEditable(true);
        loadFileAIDComboBox.setName("loadFileAIDComboBox"); // NOI18N

        javax.swing.GroupLayout loadFileAIDPanelLayout = new javax.swing.GroupLayout(loadFileAIDPanel);
        loadFileAIDPanel.setLayout(loadFileAIDPanelLayout);
        loadFileAIDPanelLayout.setHorizontalGroup(
            loadFileAIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadFileAIDPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loadFileAIDComboBox, 0, 316, Short.MAX_VALUE)
                .addContainerGap())
        );
        loadFileAIDPanelLayout.setVerticalGroup(
            loadFileAIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadFileAIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        securityDomainAIDPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("securityDomainAIDPanel.border.title"))); // NOI18N
        securityDomainAIDPanel.setName("securityDomainAIDPanel"); // NOI18N

        securityDomainAIDComboBox.setEditable(true);
        securityDomainAIDComboBox.setName("securityDomainAIDComboBox"); // NOI18N

        javax.swing.GroupLayout securityDomainAIDPanelLayout = new javax.swing.GroupLayout(securityDomainAIDPanel);
        securityDomainAIDPanel.setLayout(securityDomainAIDPanelLayout);
        securityDomainAIDPanelLayout.setHorizontalGroup(
            securityDomainAIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(securityDomainAIDPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(securityDomainAIDComboBox, 0, 316, Short.MAX_VALUE)
                .addContainerGap())
        );
        securityDomainAIDPanelLayout.setVerticalGroup(
            securityDomainAIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(securityDomainAIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout aidsPanelLayout = new javax.swing.GroupLayout(aidsPanel);
        aidsPanel.setLayout(aidsPanelLayout);
        aidsPanelLayout.setHorizontalGroup(
            aidsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aidsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aidsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(securityDomainAIDPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadFileAIDPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        aidsPanelLayout.setVerticalGroup(
            aidsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aidsPanelLayout.createSequentialGroup()
                .addComponent(loadFileAIDPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(securityDomainAIDPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loadParametersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("loadParametersPanel.border.title"))); // NOI18N
        loadParametersPanel.setName("loadParametersPanel"); // NOI18N

        loadParametersScrollPanel.setName("loadParametersScrollPanel"); // NOI18N

        loadParametersTextArea.setColumns(20);
        loadParametersTextArea.setRows(2);
        loadParametersTextArea.setName("loadParametersTextArea"); // NOI18N
        loadParametersScrollPanel.setViewportView(loadParametersTextArea);

        javax.swing.GroupLayout loadParametersPanelLayout = new javax.swing.GroupLayout(loadParametersPanel);
        loadParametersPanel.setLayout(loadParametersPanelLayout);
        loadParametersPanelLayout.setHorizontalGroup(
            loadParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadParametersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loadParametersScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );
        loadParametersPanelLayout.setVerticalGroup(
            loadParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadParametersScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loadParametersPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aidsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aidsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadParametersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aidsPanel;
    private javax.swing.JComboBox loadFileAIDComboBox;
    private javax.swing.JPanel loadFileAIDPanel;
    private javax.swing.JPanel loadParametersPanel;
    private javax.swing.JScrollPane loadParametersScrollPanel;
    private javax.swing.JTextArea loadParametersTextArea;
    private javax.swing.JComboBox securityDomainAIDComboBox;
    private javax.swing.JPanel securityDomainAIDPanel;
    // End of variables declaration//GEN-END:variables

}
